### ISSUE TITLE
FEATURE Shopify Admin API PHP Library to integrate

### ISSUE THREAD

**Issue by jsirish** [dynamic/silverstripe-shopify#40]
The module will include a PHP API client to interact with the [Shopify Admin API](https://shopify.dev/docs/admin-api). The Admin API provides extensive access to data about individual Shopify stores, and will allow us to add custom features to the Shopify user experience.

- Read and write Shopify store information, including data about products, inventory, orders, shipping, and more.
- The Admin API is available through GraphQL and REST.

The ideal solution would be to serve as a wrapper for a mature, maintained Shopify PHP API library. Shopify lists [existing Shopify PHP API classes](https://shopify.dev/tools/libraries/admin-api#php) that can be used to easily interface with the Admin API.

Initial proposed library to explore is [phpclassic/php-shopify](https://github.com/phpclassic/php-shopify). This library appears to be mature, active, and was referenced most often during initial Shopify PHP research in articles and message boards. This module seems to offer both REST and GraphQL interfaces, Dynamic will need to decide which route to pursue.

API credentials would ideally be set per server in the environment file. If this is impractical, credentials could be stored in config yaml files, with different credentials set per website environment mode - typically one set for Test, one set for Live.
The client would utilize functions from the PHP library to sync data between the website and Shopify, such as product records and customer information.

The client would utilize functions from the PHP library to sync data between the website and Shopify, such as product records and customer information.

**Comment by jsirish** [comment]
In discussions, @mak001 was leaning towards using the REST implementation of the API

**Comment by muskie9** [comment]
resolved via #56
