### ISSUE TITLE
FEATURE Shopify Data Sync

### ISSUE THREAD

**Issue by jsirish** [dynamic/silverstripe-shopify#41]
The module will need to be able to sync data from Shopify to the website to create and display the products on the website. Data sync will utilize the Silverstripe Shopify Admin API Client.

The following record types would be imported:

- ShopifyProduct
- ShopifyVariant
- ShopifyCollection
- ShopifyFile
- ShopifyMember

Records deleted in Shopify would be removed from the Silverstripe website, and all related content records would cascade delete.

### Import Task
A task is created to sync the entire product catalog from Shopify to the website via the Shopify API. This would likely be a task set to run via cron or a queued job.

### Sync from Shopify
On a product record in the CMS, there should be a button to sync the current product from Shopify. This will be useful for occasions where a product is updated in Shopify, allowing the record in the CMS to be updated without a full data sync.

**Comment by mak001** [comment]
This is functional, but there are other tickets related to clean up and stability. Closing this as anything new can go into its own ticket, if it hasn't already.
