### ISSUE TITLE
FEATURE Order History

### ISSUE THREAD

**Issue by jsirish** [dynamic/silverstripe-shopify#43]
Smaller installations may not require Order History, so this could be an add-on module to a base silverstripe-shopify installation.

For larger installations, an authenticated customer should be able to view their order history. Currently, Shopify does not offer a customer portal as part of its platform.

### API On Demand
Via the Shopify API, the Silverstripe website will fetch the order history for the customer, and display it on the page. Order history will not be stored in the Silverstripe database, only referenced on demand. This would require SSO implementation.

[Full field list](https://shopify.dev/docs/admin-api/rest/reference/orders/order).

**Comment by mak001** [comment]
This was mostly done in #57. It still has some issues, but they are outlined in #64
