### ISSUE TITLE
FEATURE File to Image for CMS Thumbnail

### ISSUE THREAD

**Issue by jsirish** [dynamic/silverstripe-shopify#45]
I'm currently using File for the Images/Videos from Shopify. However, `File` does not have the method CMSThumbnail() so the Model Admin summary fields show a blank image.

Is there a way, via a getImage() method, to grab the first file, check that it's an image, and then cast or render as an Image? We could then display the thumbnail in the ModelAdmin.

**Comment by mak001** [comment]
This was done in #73
