### ISSUE TITLE
BUG ShopifyImportTask - task seems to error if no Collections exist (or are in the API sales channel)

### ISSUE THREAD

**Issue by jsirish** [dynamic/silverstripe-shopify#94]
On a new client store, the initial ShopifyImportTask failed:

`Trying to get property 'collections' of non-object`

Line 102 - `foreach ($collections['body']->data->collections->edges as $shopifyCollection) {`

Once the initial collection was created and added to the API sales channel, the import worked as expected

**Comment by muskie9** [comment]
Probably need to add some logic checks to ensure those properties exist on the result vs just assuming it's there.

**Comment by jsirish** [comment]
this may have been an API permission issue instead - setting Product Listings to `read` access in the admin API resolved the issue.

Will leave on here for now In case it comes up again.

**Comment by muskie9** [comment]
Closing as no additional issues reported. If this crops back up we can re-open this or open a new ticket.
